---
name: Checks

on: [push]

jobs:
    # The id of the job.
    test-lint:
        # The name that we will see within the github actions interface
        name: Test and Lint
        # the runner that we are going to be running the job on, ubuntu-20.04 has docker-compose (installed)
        runs-on: ubuntu-20.04
        steps:
            - name: Login toDocker Hub
              # uses : allow you to use another pre-made action that's provided in the github actions reository
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Checkout
              # this action check our code out inside our github actions job, we need to check if the code is available for us to run the next step
              uses: actions/checkout@v2
            - name: Test
              run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
            - name: Lint
              run: docker-compose run --rm app sh -c "flake8"
                